<?php

declare(strict_types=1);

namespace App\Puzzle\Theme;

use App\Enum\Puzzle\ThemeCategory;

/**
 * The official Lichess puzzle themes, generated from lila's `modules/puzzle/.../PuzzleTheme.scala`
 * (keys, categories, order) and its `translation/{source,dest/fr-FR}/puzzleTheme.xml` files.
 *
 * "mix" (no filter) is not a theme here; "mate" is listed once, under Mates (Lichess also shows it
 * under Goals). The keys are the ones used in the CSV export's Themes column.
 */
final class ThemeCatalog
{
    /** @var list<array{string, ThemeCategory, string, string, string, string}> key, category, EN label, FR label, EN description, FR description */
    public const THEMES = [
        ['opening', ThemeCategory::Phases, 'Opening', 'Ouverture', 'A tactic during the first phase of the game.', 'Une tactique durant la première phase de la partie.'],
        ['middlegame', ThemeCategory::Phases, 'Middlegame', 'Milieu de jeu', 'A tactic during the second phase of the game.', 'Une tactique pendant la seconde phase de la partie.'],
        ['endgame', ThemeCategory::Phases, 'Endgame', 'Finale', 'A tactic during the last phase of the game.', 'Une tactique lors de la dernière phase du jeu.'],
        ['rookEndgame', ThemeCategory::Phases, 'Rook endgame', 'Finale de Tours', 'An endgame with only rooks and pawns.', 'Une finale avec seulement des Tours et des pions.'],
        ['bishopEndgame', ThemeCategory::Phases, 'Bishop endgame', 'Finale de Fous', 'An endgame with only bishops and pawns.', 'Une finale avec seulement des Fous et des pions.'],
        ['pawnEndgame', ThemeCategory::Phases, 'Pawn endgame', 'Finale de pions', 'An endgame with only pawns.', 'Une finale avec seulement des pions.'],
        ['knightEndgame', ThemeCategory::Phases, 'Knight endgame', 'Finale de Cavaliers', 'An endgame with only knights and pawns.', 'Une finale avec seulement des Cavaliers et des pions.'],
        ['queenEndgame', ThemeCategory::Phases, 'Queen endgame', 'Finale de Dames', 'An endgame with only queens and pawns.', 'Une finale avec seulement des Dames et des pions.'],
        ['queenRookEndgame', ThemeCategory::Phases, 'Queen and Rook', 'Dames et Tours', 'An endgame with only queens, rooks and pawns.', 'Une finale avec seulement des Dames, Tours et pions.'],
        ['advancedPawn', ThemeCategory::Motifs, 'Advanced pawn', 'Pion avancé', 'One of your pawns is deep into the opponent position, maybe threatening to promote.', 'Un pion se promouvant ou menaçant d\'être promu est essentiel à la tactique.'],
        ['attackingF2F7', ThemeCategory::Motifs, 'Attacking f2 or f7', 'Attaque sur f2 ou f7', 'An attack focusing on the f2 or f7 pawn, such as in the fried liver opening.', 'Une attaque sur le pion f2 ou f7, comme dans l\'attaque fegatello/Fried Liver.'],
        ['capturingDefender', ThemeCategory::Motifs, 'Capture the defender', 'Capturez le défenseur', 'Removing a piece that is critical to defence of another piece, allowing the now undefended piece to be captured on a following move.', 'Retire une pièce essentielle à la défense d\'une autre pièce, permettant à la pièce non protégée d\'être capturée au coup suivant.'],
        ['discoveredAttack', ThemeCategory::Motifs, 'Discovered attack', 'Attaque à la découverte', 'Moving a piece (such as a knight), that previously blocked an attack by a long range piece (such as a rook), out of the way of that piece.', 'Déplacer une pièce qui bloquait auparavant une attaque par une autre pièce à longue portée, comme un Cavalier hors du champ d\'une Tour.'],
        ['doubleCheck', ThemeCategory::Motifs, 'Double check', 'Échec double', 'Checking with two pieces at once, as a result of a discovered attack where both the moving piece and the unveiled piece attack the opponent\'s king.', 'Faire échec avec deux pièces à la fois, à la suite d\'une attaque à la découverte où la pièce mobile et la pièce dévoilée attaquent le Roi adverse.'],
        ['exposedKing', ThemeCategory::Motifs, 'Exposed king', 'Roi exposé', 'A tactic involving a king with few defenders around it, often leading to checkmate.', 'Une tactique impliquant un Roi avec peu de défenseurs autour de lui, menant souvent à l\'échec et mat.'],
        ['fork', ThemeCategory::Motifs, 'Fork', 'Fourchette', 'A move where a piece attacks two or more opposing pieces simultaneously.', 'Un coup où une pièce attaque simultanément deux pièces ou plus.'],
        ['hangingPiece', ThemeCategory::Motifs, 'Hanging piece', 'Pièce en prise', 'A tactic involving an opponent piece being undefended or insufficiently defended and free to capture.', 'Une tactique impliquant une pièce adverse non protégée ou insuffisamment défendue et libre d\'être capturée.'],
        ['kingsideAttack', ThemeCategory::Motifs, 'Kingside attack', 'Attaque sur l\'aile roi', 'An attack of the opponent\'s king, after they castled on the king side.', 'Une attaque du Roi adverse, après qu\'il a fait le petit roque.'],
        ['pin', ThemeCategory::Motifs, 'Pin', 'Clouage', 'A tactic involving pins, where a piece is unable to move without revealing an attack on a higher value piece.', 'Une tactique impliquant des clouages, où une pièce est incapable de se déplacer sans qu\'une pièce de valeur supérieure soit attaquée.'],
        ['queensideAttack', ThemeCategory::Motifs, 'Queenside attack', 'Attaque sur l\'aile dame', 'An attack of the opponent\'s king, after they castled on the queen side.', 'Une attaque du Roi adverse, après qu\'il a fait le grand roque.'],
        ['sacrifice', ThemeCategory::Motifs, 'Sacrifice', 'Sacrifice', 'A tactic involving giving up material in the short-term, to gain an advantage again after a forced sequence of moves.', 'Une tactique consistant à donner du matériel à court terme, pour gagner un avantage après une séquence de coups forcés.'],
        ['skewer', ThemeCategory::Motifs, 'Skewer', 'Enfilade', 'A motif involving a high value piece being attacked, moving out the way, and allowing a lower value piece behind it to be captured or attacked, the inverse of a pin.', 'Un motif impliquant l\'attaque d\'une pièce de grande valeur qui en se dégageant permet la capture ou l\'attaque d\'une pièce de moindre valeur située derrière elle, l\'inverse d\'un clouage.'],
        ['trappedPiece', ThemeCategory::Motifs, 'Trapped piece', 'Pièce enfermée', 'A piece is unable to escape capture as it has limited moves.', 'Une pièce forcément capturée car incapable de s\'échapper.'],
        ['attraction', ThemeCategory::Advanced, 'Attraction', 'Attraction', 'An exchange or sacrifice encouraging or forcing an opponent piece to a square that allows a follow-up tactic.', 'Un échange ou un sacrifice encourageant ou forçant une pièce adverse à bouger sur une case, permettant une tactique.'],
        ['clearance', ThemeCategory::Advanced, 'Clearance', 'Dégagement', 'A move, often with tempo, that clears a square, file or diagonal for a follow-up tactical idea.', 'Un coup, souvent avec tempo, qui libère une case, une colonne ou une diagonale en vue d\'une idée tactique.'],
        ['collinearMove', ThemeCategory::Advanced, 'Collinear move', 'Coup colinéaire', 'Two opposing pieces face each other, and one slides along the line of attack without capturing the enemy piece.', 'Deux pièces opposées se font face et l\'une des deux se déplace sur la même ligne sans capturer l\'autre pièce.'],
        ['discoveredCheck', ThemeCategory::Advanced, 'Discovered check', 'Échec à la découverte', 'Move a piece to reveal a check from a hidden attacking piece, which often leads to a decisive advantage.', 'En se déplaçant, une pièce permet à une autre pièce de mettre le roi adverse en échec et d\'obtenir souvent un avantage décisif.'],
        ['defensiveMove', ThemeCategory::Advanced, 'Defensive move', 'Coup défensif', 'A precise move or sequence of moves that is needed to avoid losing material or another advantage.', 'Un coup ou une séquence de coups précis qui est nécessaire pour éviter de perdre du matériel ou un autre avantage.'],
        ['deflection', ThemeCategory::Advanced, 'Deflection', 'Déviation', 'A move that distracts an opposing piece from another duty that it performs, such as guarding a key square. Sometimes also called "overloading".', 'Un coup qui dévie une pièce de l\'adversaire d\'une tâche qu\'elle assure, comme la protection d\'une case-clé.'],
        ['interference', ThemeCategory::Advanced, 'Interference', 'Interception', 'Moving a piece between two opponent pieces to leave one or both opponent pieces undefended, such as a knight on a defended square between two rooks.', 'Déplacer une pièce entre deux pièces adverses pour en laisser l\'une ou les deux non protégées, comme un Cavalier sur une case défendue entre deux Tours.'],
        ['intermezzo', ThemeCategory::Advanced, 'Intermezzo', 'Coup intermédiaire', 'Instead of playing the expected move, first interpose another move posing an immediate threat that the opponent must answer. Also known as "Zwischenzug" or "In between".', 'Au lieu de jouer le coup attendu, jouez d\'abord un autre coup posant une menace immédiate à laquelle l\'adversaire doit répondre. Aussi connu sous le nom de "Zwischenzug".'],
        ['quietMove', ThemeCategory::Advanced, 'Quiet move', 'Coup silencieux', 'A move that does not check, capture, or create an immediate threat to capture. Instead, it prepares a hidden and unavoidable threat for a later move.', 'Un mouvement qui ne fait pas échec ni n\'est une capture, mais qui prépare une menace inévitable.'],
        ['xRayAttack', ThemeCategory::Advanced, 'X-Ray attack', 'Attaque « rayons X »', 'A piece attacks or defends a square, through an enemy piece.', 'Une pièce attaque ou défend une case, à travers une pièce ennemie.'],
        ['zugzwang', ThemeCategory::Advanced, 'Zugzwang', 'Zugzwang', 'The opponent is limited in the moves they can make, and all moves worsen their position.', 'L\'adversaire est limité dans les mouvements qu\'il peut effectuer, et tous les coups aggravent sa position.'],
        ['mate', ThemeCategory::Mates, 'Checkmate', 'Mat', 'Win the game with style.', 'Gagnez la partie avec classe.'],
        ['mateIn1', ThemeCategory::Mates, 'Mate in 1', 'Mat en 1', 'Deliver checkmate in one move.', 'Matez en un coup.'],
        ['mateIn2', ThemeCategory::Mates, 'Mate in 2', 'Mat en 2', 'Deliver checkmate in two moves.', 'Matez en deux coups.'],
        ['mateIn3', ThemeCategory::Mates, 'Mate in 3', 'Mat en 3', 'Deliver checkmate in three moves.', 'Matez en trois coups.'],
        ['mateIn4', ThemeCategory::Mates, 'Mate in 4', 'Mat en 4', 'Deliver checkmate in four moves.', 'Matez en quatre coups.'],
        ['mateIn5', ThemeCategory::Mates, 'Mate in 5 or more', 'Mat en 5 ou plus', 'Figure out a long mating sequence.', 'Trouvez une longue séquence de coups menant au mat.'],
        ['anastasiaMate', ThemeCategory::MateThemes, 'Anastasia\'s mate', 'Mat d\'Anastasie', 'A knight and rook or queen team up to trap the opposing king between the side of the board and a friendly piece.', 'Un Cavalier et une Tour ou une Dame s\'associent pour piéger le Roi adverse entre le bord de l\'échiquier et une pièce amie.'],
        ['arabianMate', ThemeCategory::MateThemes, 'Arabian mate', 'Mat des Arabes', 'A knight and a rook team up to trap the opposing king on a corner of the board.', 'Un Cavalier et une Tour s\'associent pour piéger le Roi adverse dans un coin de l\'échiquier.'],
        ['backRankMate', ThemeCategory::MateThemes, 'Back rank mate', 'Mat du couloir', 'Checkmate the king on the home rank, when it is trapped there by its own pieces.', 'Matez le Roi sur la dernière rangée, lorsqu\'il est piégé par ses propres pièces.'],
        ['balestraMate', ThemeCategory::MateThemes, 'Balestra mate', 'Mat de l\'arbalète', 'A bishop delivers the checkmate, while a queen blocks the remaining escape squares', 'Un fou fait échec tandis que la dame contrôle les cases de fuite.'],
        ['blindSwineMate', ThemeCategory::MateThemes, 'Blind Swine mate', 'Mat des deux tours', 'Two rooks team up to mate the king in an area of 2 by 2 squares.', 'Deux tours matent le roi adverse dans un espace de deux cases par deux cases.'],
        ['bodenMate', ThemeCategory::MateThemes, 'Boden\'s mate', 'Mat de Boden', 'Two attacking bishops on criss-crossing diagonals deliver mate to a king obstructed by friendly pieces.', 'Deux Fous contrôlant des diagonales qui s\'entrecroisent matent un Roi bloqué par ses propres pièces.'],
        ['cornerMate', ThemeCategory::MateThemes, 'Corner mate', 'Mat en coin', 'Confine the king to the corner using a rook or queen, and use a knight to deliver the checkmate.', 'Utilisez la tour et la dame pour confiner le roi dans le coin de l\'échiquier, puis faites mat avec le cavalier.'],
        ['doubleBishopMate', ThemeCategory::MateThemes, 'Double bishop mate', 'Mat des deux Fous', 'Two attacking bishops on adjacent diagonals deliver mate to a king obstructed by friendly pieces.', 'Deux Fous contrôlant des diagonales adjacentes matent un Roi bloqué par ses propres pièces.'],
        ['dovetailMate', ThemeCategory::MateThemes, 'Dovetail mate', 'Mat de Cozio', 'A queen delivers mate to an adjacent king, whose only two escape squares are obstructed by friendly pieces.', 'Une Dame mate un Roi placé sur une case adjacente, les deux seules cases de fuite étant occupées par des pièces amies.'],
        ['epauletteMate', ThemeCategory::MateThemes, 'Epaulette mate', 'Mat des épaulettes', 'Two adjacent escape squares for a checked king are occupied by other pieces.', 'Deux cases de fuite des deux côtés du roi en échec sont occupées par des pièces.'],
        ['hookMate', ThemeCategory::MateThemes, 'Hook mate', 'Mat du hameçon', 'Checkmate using a rook, knight, and pawn, where an opposing pawn blocks the king\'s escape.', 'Faire mat en utilisant une tour, un cavalier et un pion lorsque le roi adverse est bloqué par un de ses pions.'],
        ['killBoxMate', ThemeCategory::MateThemes, 'Kill box mate', 'Mat par mise en boîte', 'A rook is next to the enemy king and supported by a queen that also blocks the king\'s escape squares. The rook and the queen catch the enemy king in a 3 by 3 "kill box".', 'La tour, protégée par la dame, met le roi adverse en échec et la dame bloque la seule case de fuite du roi (le roi est enfermé dans une boîte de 3 cases par 3 cases formée par la tour et la dame).'],
        ['pillsburysMate', ThemeCategory::MateThemes, 'Pillsbury\'s mate', 'Mat de Pillsbury', 'A rook delivers checkmate to the king, while a bishop helps confine it.', 'La tour met le roi mat avec l\'aide du fou.'],
        ['morphysMate', ThemeCategory::MateThemes, 'Morphy\'s mate', 'Mat de Morphy', 'A bishop delivers checkmate to the king, while a rook helps confine it.', 'Le fou met le roi mat avec l\'aide de la tour.'],
        ['operaMate', ThemeCategory::MateThemes, 'Opera mate', 'Mat de l\'opéra', 'Check the king with a rook and use a bishop to defend the rook.', 'Protégée par le fou, la tour met le roi adverse échec et mat.'],
        ['swallowstailMate', ThemeCategory::MateThemes, 'Swallow\'s tail mate', 'Mat du guéridon', 'A checkmate pattern that visually resembles the appearance of a swallow’s tail, similar to a V shape.', 'Motif de mat qui ressemble visuellement à un guéridon (une petite table soutenue par un pied central).'],
        ['triangleMate', ThemeCategory::MateThemes, 'Triangle mate', 'Mat du triangle', 'The queen and rook, one square away from the enemy king, are on the same rank or file, separated by one square, forming a triangle.', 'La dame et la tour, à une case de distance du roi adverse, sont sur la même rangée ou colonne et donnent mat en formant un triangle.'],
        ['vukovicMate', ThemeCategory::MateThemes, 'Vuković mate', 'Mat de Vukovic', 'A rook and knight team up to mate the king. The rook delivers mate while supported by a third piece, and the knight is used to block the king\'s escape squares.', 'Une tour et un cavalier collaborent pour mater le roi adverse. Protégée par une troisième pièce, la tour fait mat, car le cavalier bloque la case de fuite du roi.'],
        ['smotheredMate', ThemeCategory::MateThemes, 'Smothered mate', 'Mat à l\'étouffée', 'A checkmate delivered by a knight in which the mated king is unable to move because it is surrounded (or smothered) by its own pieces.', 'Un mat délivré par un Cavalier dans lequel le Roi est incapable de s\'échapper parce qu\'il est entouré (ou étouffé) par ses propres pièces.'],
        ['castling', ThemeCategory::SpecialMoves, 'Castling', 'Roque', 'Bring the king to safety, and deploy the rook for attack.', 'Mettez votre Roi en sécurité et développez vos Tours pour attaquer.'],
        ['enPassant', ThemeCategory::SpecialMoves, 'En passant', 'Prise en passant', 'A tactic involving the en passant rule, where a pawn can capture an opposing pawn that has just moved next to it with its initial two-square move.', 'Tactique utilisant la « prise en passant », où un pion peut capturer un pion adverse qui vient de se placer à côté de lui en se déplaçant de deux cases au premier coup.'],
        ['promotion', ThemeCategory::SpecialMoves, 'Promotion', 'Promotion', 'Promote one of your pawns to a queen, rook or minor piece.', 'Promouvez l\'un de vos pions en une dame, une tour ou une pièce mineure.'],
        ['underPromotion', ThemeCategory::SpecialMoves, 'Underpromotion', 'Sous-promotion', 'Promotion to a knight, bishop, or rook.', 'Promotion en Cavalier, Fou ou Tour.'],
        ['equality', ThemeCategory::Goals, 'Equality', 'Égalité', 'Come back from a losing position, and secure a draw or a balanced position. (eval ≤ 200cp)', 'Revenir d\'une position perdante et assurer une nulle ou une position équilibrée. (évaluation ≤ 200cp)'],
        ['advantage', ThemeCategory::Goals, 'Advantage', 'Avantage', 'Seize your chance to get a decisive advantage. (200cp ≤ eval ≤ 600cp)', 'Saisissez votre chance d\'obtenir un avantage décisif. (200cp ≤ évaluation ≤ 600cp)'],
        ['crushing', ThemeCategory::Goals, 'Crushing', 'Écrasant', 'Spot the opponent blunder to obtain a crushing advantage. (eval ≥ 600cp)', 'Repérez la gaffe de l\'adversaire pour obtenir un avantage écrasant. (évaluation > 600cp)'],
        ['oneMove', ThemeCategory::Lengths, 'One-move puzzle', 'Problème à un coup', 'A puzzle that is only one move long.', 'Un problème qui ne dure qu\'un coup.'],
        ['short', ThemeCategory::Lengths, 'Short puzzle', 'Court problème', 'Two moves to win.', 'Victoire en deux coups.'],
        ['long', ThemeCategory::Lengths, 'Long puzzle', 'Long problème', 'Three moves to win.', 'Victoire en trois coups.'],
        ['veryLong', ThemeCategory::Lengths, 'Very long puzzle', 'Très long problème', 'Four moves or more to win.', 'Quatre coups ou plus pour gagner.'],
        ['master', ThemeCategory::Origin, 'Master games', 'Parties de maîtres', 'Puzzles from games played by titled players.', 'Problèmes tirés de parties jouées par des joueurs titrés'],
        ['masterVsMaster', ThemeCategory::Origin, 'Master vs Master games', 'Parties jouées entre maîtres', 'Puzzles from games between two titled players.', 'Problèmes tirés de parties entre deux joueurs titrés'],
        ['superGM', ThemeCategory::Origin, 'Super GM games', 'Parties de super GM', 'Puzzles from games played by the best players in the world.', 'Problèmes issus de parties des meilleurs joueurs du monde.'],
    ];
}
