<?php

declare(strict_types=1);

namespace App\Tests\Unit\Repertoire\Srs;

use App\Enum\Repertoire\CardState;
use App\Enum\Repertoire\Rating;
use App\Repertoire\Srs\Card;
use App\Repertoire\Srs\Fsrs;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * App\Repertoire\Srs\Fsrs against py-fsrs 6.3.2 (tests/Fixtures/Repertoire/fsrs-vectors.json,
 * generated by fsrs-vectors.py next to it, without fuzzing).
 *
 * @phpstan-type Step array{at: string, rating: int, retrievability: float, card: array{state: int, step: int|null, stability: float, difficulty: float, due: string, lastReview: string}}
 */
final class FsrsTest extends TestCase
{
    private const VECTORS = __DIR__.'/../../../Fixtures/Repertoire/fsrs-vectors.json';
    /** Relative tolerance on stability, difficulty and retrievability (the same arithmetic in both). */
    private const EPSILON = 1e-12;

    /**
     * @return iterable<string, array{list<Step>}>
     */
    public static function vectors(): iterable
    {
        /** @var array{cases: list<array{name: string, steps: list<Step>}>} $data */
        $data = json_decode((string) file_get_contents(self::VECTORS), true, flags: \JSON_THROW_ON_ERROR);
        foreach ($data['cases'] as $case) {
            yield $case['name'] => [$case['steps']];
        }
    }

    /**
     * @param list<Step> $steps
     */
    #[DataProvider('vectors')]
    public function testEachReviewMatchesPyFsrs(array $steps): void
    {
        $fsrs = new Fsrs(fuzz: false);
        $card = Card::fresh(new \DateTimeImmutable($steps[0]['at']));

        foreach ($steps as $i => $step) {
            $at = new \DateTimeImmutable($step['at']);
            self::assertEqualsWithDelta($step['retrievability'], $fsrs->retrievability($card, $at), self::EPSILON, "retrievability before review $i");
            $card = $fsrs->review($card, Rating::from($step['rating']), $at);
            $expected = $step['card'];

            self::assertSame(CardState::from($expected['state']), $card->state, "state after review $i");
            self::assertSame($expected['step'], $card->step, "step after review $i");
            self::assertEqualsWithDelta($expected['stability'], (float) $card->stability, abs($expected['stability']) * self::EPSILON, "stability after review $i");
            self::assertEqualsWithDelta($expected['difficulty'], (float) $card->difficulty, self::EPSILON * 10, "difficulty after review $i");
            self::assertSame((new \DateTimeImmutable($expected['due']))->getTimestamp(), $card->due->getTimestamp(), "due after review $i");
            self::assertSame((new \DateTimeImmutable($expected['lastReview']))->getTimestamp(), $card->lastReview?->getTimestamp(), "last review $i");
        }
    }

    public function testTheVectorsCoverEveryStateAndRating(): void
    {
        $states = $ratings = [];
        foreach (self::vectors() as [$steps]) {
            foreach ($steps as $step) {
                $states[$step['card']['state']] = true;
                $ratings[$step['rating']] = true;
            }
        }
        ksort($states);
        ksort($ratings);

        self::assertSame([1, 2, 3], array_keys($states));
        self::assertSame([1, 2, 3, 4], array_keys($ratings));
    }

    public function testFuzzSpreadsReviewIntervalsWithinPyFsrsBounds(): void
    {
        $start = new \DateTimeImmutable('2026-01-01 09:00:00', new \DateTimeZone('UTC'));
        $plain = (new Fsrs(fuzz: false))->review(Card::fresh($start), Rating::Easy, $start);
        $days = (int) (($plain->due->getTimestamp() - $start->getTimestamp()) / 86400);
        self::assertSame(8, $days, 'initial stability 8.2956 days: 8 days at 90 %');

        // 8 days: delta = 1 + 0.15 x 4.5 + 0.1 x 1 = 1.775, bounds 6 and 10. py-fsrs draws
        // random() x (10 - 6 + 1) + 6 and rounds it: the top draws reach 11, and so does this port.
        $days = static fn (float $random): int => (int) (((new Fsrs(random: static fn (): float => $random))->review(Card::fresh($start), Rating::Easy, $start)->due->getTimestamp() - $start->getTimestamp()) / 86400);
        self::assertSame(6, $days(0.0));
        self::assertSame(8, $days(0.5));
        self::assertSame(10, $days(0.89));
        self::assertSame(11, $days(0.9999));

        // Learning steps are never fuzzed.
        $learning = (new Fsrs(random: static fn (): float => 0.9999))->review(Card::fresh($start), Rating::Good, $start);
        self::assertSame(600, $learning->due->getTimestamp() - $start->getTimestamp());
    }

    public function testANewCardIsDueAtOnceAndHasNoRetrievability(): void
    {
        $now = new \DateTimeImmutable('2026-01-01 09:00:00', new \DateTimeZone('UTC'));
        $card = Card::fresh($now);

        self::assertSame([CardState::Learning, 0, null, null], [$card->state, $card->step, $card->stability, $card->difficulty]);
        self::assertTrue($card->isDue($now));
        self::assertSame(0.0, (new Fsrs())->retrievability($card, $now));
        $this->expectException(\InvalidArgumentException::class);
        new Fsrs(parameters: [0.1, 0.2]);
    }
}
